### PR TITLE
Make package publishable via NPM

### PR DESCRIPTION
**Pull request by tomyan**
Hi Miller

Here are some changes that will make it possible to publish the js-signals with NPM. There are a few ways to do this - this proposal involves the smallest amount of change to the existing structure and build that I could think of. NPM expects a tar.gz with a package.json file in the root. This change creates a version of the module in common js format in the dist folder and a package.json meta-data file in the root. With these changes, publishing to NPM would be achieved by running the following after the tag has been pushed to github (once you've set npm up to be able to publish):

```
npm publish https://github.com/millermedeiros/js-signals/tarball/vVERSION
```

Let me know if you can think of a better way to achieve this, or would prefer not to do the publishing to NPM yourself.

Thanks

Tom

### CODE REVIEW

**Comment by timoxley** [comment]
Awesome work! Though should probably just call the package 'signals'.

**Comment by tomyan** [comment]
Sounds good to me - I'd prefer to write:

```
var signals = require('signals');
```

If you add:

```
"keywords" : [ "js-signals" ]
```

..into the package.json meta-data file, then it will still come up when people search for "js-signals" in npm.

Tom

**Comment by millermedeiros** [comment]
thanks a lot, I will merge it later this week and add the keywords as well.. 

I will keep the package name as `signals` as @secoif noted to match the namespace - maybe I should even change the name of the distribution files to `signals.js` so if you are loading it as an AMD module you can just `require('signals')` the same way you would do with the common JS module.

**Comment by timoxley** [comment]
Nice. Yes, would be best to keep it as consistent as possible.

**Comment by millermedeiros** [comment]
ready to be used! http://search.npmjs.org/#/signals

I would delay forever to look into how to publish to npm without the request... thanks.

**Comment by tomyan** [comment]
Very cool - thank you.

Tom

**Comment by timoxley** [comment]
Awesome, I'm really looking forward to seeing signals in more libraries now. Yeehaw.

**Pull request merged**
